### ISSUE TITLE
[Feature Suggestion] Warning message

### ISSUE THREAD

**Issue by Bennyboy1695** [KaiKikuchi/KaisRandomTeleport#1]
Hi, i've been checking out your random tp plugin because its definitely one of the better ones i can find.
i've seen that every time you use /rtp after logging into the server after a restart it will give you the message. Maybe create a config option that will allow you to turn that off or even a permission that will say to ignore the message.

Also a countdown to how long until it teleports you would be great.

**Comment by KaiKikuchi** [comment]
Hello. Thank you for your suggestions.

Unfortunately I can't add a countdown to how long until it teleports you because it's not always the same. It should be 5 seconds, but at the same time it searches for a suitable location.

I will update the repository shortly.

**Comment by KaiKikuchi** [comment]
Added a config option for the warning message in version 1.7

**Comment by Bennyboy1695** [comment]
Thank you for such a quick reply and update :smile:
Not a coder but is there no way of having it search for safe locations on startup and store them in a local file or if essentials is installed to hook into the essentials safe location ?

**Comment by KaiKikuchi** [comment]
Sorry but I don't understand what you mean. I need more details. Log a new issue ticket.
