### ISSUE TITLE
[Feature Suggestion] Safe Location searching

### ISSUE THREAD

**Issue by Bennyboy1695** [KaiKikuchi/KaisRandomTeleport#2]
With the current setup it finds the safe locations after you enter the command /rtp
What im wondering is whether or not it would be able to either on server startup find the safe locations and store them into a local file. Or if the plugin essentials is installed, hook into the safelocation coding in that.

**Comment by KaiKikuchi** [comment]
The locations are randomly searched after the /rtp command is issued, so this is not possible for various reasons.

Also I don't understand the need for this.

**Comment by Bennyboy1695** [comment]
There isn't a need for it, but would reduce the search time on command run.

**Comment by KaiKikuchi** [comment]
I'm sorry but I can't do that. Also it's not necessary because it should find a safe location before 5 seconds. Also a safe location could be not that safe after a couple of minutes. Lava? Players may place blocks on that location?

**Comment by Bennyboy1695** [comment]
Thats true i didn't think of blocks placed after safe locations were found.
Thank you for being open to the suggestions though :smile:
