### ISSUE TITLE
Suffocation

### ISSUE THREAD

**Issue by Mangledpotato** [KaiKikuchi/KaisRandomTeleport#4]
There was an issue where doing the /rtp put me in a tree that caused me to suffocate, but i broke free while chat was spammed with the "JUST HOLD ON, YOU'LL BE SAVED" every second, then after awhile from escaping, it randomly teleported me.

**Comment by KaiKikuchi** [comment]
When reporting a bug, you should post your server log. Also you need to specify your server version, plugin's version, and any other useful info.

That message appears when you get hit just after random teleporting. You get healed and teleported to the previous location, then it'll teleport you to another random location. So, it's totally fine. If there's some exception in your server log, then you can post it.
