### ISSUE TITLE
Configurable or a Small prefix

### ISSUE THREAD

**Issue by DarkBlade177** [KaiKikuchi/KaisRandomTeleport#5]
![image](https://cloud.githubusercontent.com/assets/18588529/20235086/1869620c-a870-11e6-93ee-0397fdcb4dd1.png)
This is too big, is there a way to reduce it or change it?

Like `[RTP]` or `[KaiRTP]`

**Comment by NathanAdhitya** [comment]
psst you know that you can edit the source and recompile it? :P

**Comment by DarkBlade177** [comment]
i dont know  how :D

**Comment by KaiKikuchi** [comment]
Added in version 1.7.2
